<?php
$date_array_m = array("tooth"		=>	array(  "title"	=>	"Zahnvorsorge-Untersuchung",
											"years"	=>	18,
											"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/zahnmedizin/rund_um_den_zahn/wie_oft_zum_zahnarzt.html?p=3",
										 ),
					"health" 	=>	array(	"title"	=>	"Gesundheits-Checkup",
											"years"	=>	35,
											"frequency"	=>	"Alle 2 Jahre",
											"add_year"	=>	"2",
											"link"		=>	"http://www.onmeda.de/arztbesuch/untersuchung/gesundheits_checkup.html",
										 ),
					"dermal" 	=>	array(	"title"	=>	"Haut-Untersuchung",
											"years"	=>	35,
											"frequency"	=>	"Alle 2 Jahre",
											"add_year"	=>	"2",
											"link"		=>	"http://www.onmeda.de/arztbesuch/vorsorge/krebsvorsorge/hautkrebs_frueherkennung.html?p=3",
										 ),
					"prostate"	=>	array(	"title"	=>	"Prostata-/Genitaluntersuchung",
															"years"	=>	45,
															"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/gesund_leben/maennergesundheit/vorsorge_maenner/prostatakrebs_frueherkennung.html",
														 ),
					"rectum" 	=>	array(	"title"	=>	"Rektum-Untersuchung",
											"years"	=>	50,
											"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/gesund_leben/maennergesundheit/vorsorge_maenner/darmkrebs_frueherkennung.html?p=4",
										 ),
					"blood" 	=>	array(	"title"	=>	"Okkultbluttest/H&auml;mocculttest",
											"years"	=>	50,
											"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/arztbesuch/vorsorge/krebsvorsorge/haemocculttest.html?p=1",
										 ),
					"colonoscopy" 	=>	array(	"title"	=>	"Darmspiegelung",
											"years"	=>	55,
											"frequency"	=>	"2 Untersuchungen im Abstand von 10 Jahren",
											"add_year"	=>	"10",
											"link"		=>	"http://www.onmeda.de/arztbesuch/untersuchung/darmspiegelung.html?p=1",
										 ),
					);
					
$date_array_w = array("tooth"		=>	array(  "title"	=>	"Zahnvorsorge-Untersuchung",
											"years"	=>	18,
											"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/zahnmedizin/rund_um_den_zahn/wie_oft_zum_zahnarzt.html?p=3",
										 ),
				"gynelogical" 	=>	array(	"title"	=>	"Gyn&auml;kologische Untersuchung",
										"years"	=>	20,
										"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/gesund_leben/frauengesundheit/vorsorge_frauen/gynaekologische_krebsfrueherkennung.html?p=",
									 ),
					"breast"	=>	array(	"title"	=>	"Brustuntersuchung",
												"years" =>	30,
											"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/gesund_leben/gesund_durch_vorsorge/krebsvorsorge/brustkrebs_frueherkennung.html?p=3",
														 ),
					"dermal" 	=>	array(	"title"	=>	"Haut-Untersuchung",
											"years"	=>	35,
											"frequency"	=>	"Alle 2 Jahre",
											"add_year"	=>	"2",
											"link"		=>	"http://www.onmeda.de/arztbesuch/vorsorge/krebsvorsorge/hautkrebs_frueherkennung.html?p=3",
										 ),
					"health" 	=>	array(	"title"	=>	"Gesundheits-Checkup",
											"years"	=>	35,
											"frequency"	=>	"Alle 2 Jahre",
											"add_year"	=>	"2",
											"link"		=>	"http://www.onmeda.de/arztbesuch/untersuchung/gesundheits_checkup.html",
										 ),
					"rectum" 	=>	array(	"title"	=>	"Rektum-Untersuchung",
											"years"	=>	50,
											"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/gesund_leben/maennergesundheit/vorsorge_maenner/darmkrebs_frueherkennung.html?p=4",
										 ),
					"blood" 	=>	array(	"title"	=>	"Okkultbluttest/H&auml;mocculttest",
											"years"	=>	50,
											"frequency"	=>	"J&auml;hrlich",
											"add_year"	=>	"1",
											"link"		=>	"http://www.onmeda.de/arztbesuch/vorsorge/krebsvorsorge/haemocculttest.html?p=1",
										 ),
					"mammogram" =>	array(	"title"	=>	"Mammographie-Screening",
											"years"	=>	50,
											"frequency"	=>	"Alle 2 Jahre",
											"add_year"	=>	"2",
											"link"		=>	"http://www.onmeda.de/arztbesuch/vorsorge/krebsvorsorge/mammographie.html",
										 ),
					"colonoscopy" 	=>	array(	"title"	=>	"Darmspiegelung",
											"years"	=>	55,
											"frequency"	=>	"2 Untersuchungen im Abstand von 10 Jahren",
											"add_year"	=>	"10",
											"link"		=>	"http://www.onmeda.de/arztbesuch/untersuchung/darmspiegelung.html?p=1",
										 ),
					);

?>